package holmes.darkgui;

import java.util.HashMap;

/**
 * Klasa zawiera domyślne wartości dla języka angielskiego.
 */
public class LangEngDafaultDB {
    public LangEngDafaultDB() {
    }

    public static HashMap<String, String> getDefaultEnglish() {
        HashMap<String, String> defaultEnglish = new HashMap<String, String>();

        //GUIManager:
        defaultEnglish.put("GUIM_toolboxTabName","Toolbox");
        defaultEnglish.put("GUIM_simulatorTabName","Simulator");
        defaultEnglish.put("GUIM_quicksimTabName","QuickSim");
        defaultEnglish.put("GUIM_tinvTabName","T-inv");
        defaultEnglish.put("GUIM_pinvTabName","P-inv");
        defaultEnglish.put("GUIM_mctTabName","MCT");
        defaultEnglish.put("GUIM_mcsTabName","MCS");
        defaultEnglish.put("GUIM_KnockoutTabName","Knockout");
        defaultEnglish.put("GUIM_fixTabName","NetFix");
        defaultEnglish.put("GUIM_clustersTabName","Clusters");
        defaultEnglish.put("GUIM_closingQuestion001","Net or its data have been changed since last save. Exit, save&exit or do not exit now?");
        defaultEnglish.put("GUIM_closeWindowTitle001","Project has been modified");
        defaultEnglish.put("LOGentry00001","Exiting program");
        defaultEnglish.put("GUIM_closingQuestion002","Are you sure you want to close the program?");
        defaultEnglish.put("LOGentry00002","Tools directory does not exist:");
        defaultEnglish.put("LOGentry00003","File COMMAND.ina does not exist or is corrupted.");
        defaultEnglish.put("GUI_inaProblem001","Unable to recreate COMMAND.ina.");
        defaultEnglish.put("GUI_inaProblem002","Error - COMMAND.ina");
        defaultEnglish.put("LOGentry00004","Unable to recreate COMMAND.ina. Invariants generator will work in Holmes mode only.");
        defaultEnglish.put("LOGentry00005","File COMMANDp.ina does not exist or is corrupted.");
        defaultEnglish.put("GUI_inaProblem003","Error - COMMANDp.ina");
        defaultEnglish.put("LOGentry00006","File ina.bat did not exist or was corrupted:");
        defaultEnglish.put("GUI_inaProblem004","Unable to recreate ina.bat. This is a critical error, possible write protection issues in program directory. Invariants generation using INAwin32 will most likely fail.");
        defaultEnglish.put("GUI_inaProblem005","Critical error - writing");
        defaultEnglish.put("LOGentry00007","Critical error, unable to recreate ina.bat file. Invariants generator will not work.");
        defaultEnglish.put("LOGentry00008R","Invalid path (");
        defaultEnglish.put("LOGentry00009R",") to Rscript executable file.");
        defaultEnglish.put("GUI_RscriptProblem001","Manually locate Rscript.exe");
        defaultEnglish.put("GUI_RscriptProblem002","R not installed");
        defaultEnglish.put("GUI_RscriptProblem003","Rscript.exe missing in path");
        defaultEnglish.put("GUI_RscriptProblem004","Missing executable");
        defaultEnglish.put("GUI_RscriptButton001","Select Rscript.exe");
        defaultEnglish.put("GUI_RscriptButton002tip","Please select Rscript exe, usually located in R/Rx.x.x/bin directory.");
        defaultEnglish.put("LOGentry00010R","Rscript executable file inaccessible. Some features (clusters operations) will be disabled.");
        defaultEnglish.put("LOGentry00011R","Rscript.exe manually located in");
        defaultEnglish.put("LOGentry00012R",". Settings file updated.");
        defaultEnglish.put("LOGentry00013R","Rscript.exe location unknown. Clustering procedures will not work.");
        defaultEnglish.put("GUI_simulator0001warn","Warning: simulator active. Cannot proceed until manually stopped.");
        defaultEnglish.put("GUI_simulator0002warn","Warning: XTPN simulator active. Cannot proceed until manually stopped.");

        //GUIOperations:
        defaultEnglish.put("GUIO_openProject001","Reading project file succcessful.");
        defaultEnglish.put("LOGentry00014","Unable to extract net as image. Cannot save to file:");
        defaultEnglish.put("GUIO_messageBox001","File choosing error. Cannot proceed.");
        defaultEnglish.put("LOGentry00015","File choosing error. No extension:");
        defaultEnglish.put("GUIO_warning001","\nWarning: hierarchical net structure detected. Using Holmes project is strongly advised.\nOther save format will most probably fail.\n");
        defaultEnglish.put("GUIO_warning002","Warning. There has been a problem detecting type of the Petri net.\nHolmes project file as save is highly recommended.");
        defaultEnglish.put("GUIO_warning003","Selected net file format:");
        defaultEnglish.put("GUIO_warning003b","Net real type: ");
        defaultEnglish.put("GUIO_warning003c","Suggested file format: ");
        defaultEnglish.put("GUIO_warning003d","Selected format will not contain all features of the current Petri Net. Resulting file\nwill contain reduced net or will be corrupted.\n");
        defaultEnglish.put("GUIO_warning003title","Invalid out net file format");
        defaultEnglish.put("GUIO_button001","Load invariants");
        defaultEnglish.put("GUIO_button001b","Select invariant file");
        defaultEnglish.put("GUIO_inaInv001","Net saving as .pnt file failed. There may be problems with file:");
        defaultEnglish.put("GUIO_inaInv002"," or there is no network yet.");
        defaultEnglish.put("GUIO_inaInv003","Missing net or file");
        defaultEnglish.put("GUIO_inaInv004","INAwin32.exe will now start. This may take a while. Click OK and please wait.\nWhen console shows in, please type Y, then N after invariants are computed.");
        defaultEnglish.put("GUIO_inaInv005","Please wait");
        defaultEnglish.put("LOGentry00016","Activating INAwin32.exe. Please wait, this may take a few seconds due to OS delays.");
        defaultEnglish.put("LOGentry00017","INAwin32.exe process finished. Reading results...");
        defaultEnglish.put("GUIO_inaInv006","I/O operation: activating INAwin32.exe failed.");
        defaultEnglish.put("GUIO_inaInv007","No invariants file - using INAwin32.exe failed.");
        defaultEnglish.put("GUIO_inaInv008","Save .inv file");
        defaultEnglish.put("GUIO_inaInv009","No, thanks");
        defaultEnglish.put("GUIO_inaInv010","Do you want to save generated .inv file?");
        defaultEnglish.put("GUIO_inaInv011","Save the invariants?");
        defaultEnglish.put("GUIO_inaInv012","Select invariants target path");
        defaultEnglish.put("LOGentry00018","Invariants generation successful.");
        defaultEnglish.put("GUIO_inaInv013","Missing executables in the tools directory. Required: INAwin32.exe, ina.bat and COMMAND.ina");
        defaultEnglish.put("GUIO_inaInv014","Missing files");
        defaultEnglish.put("GUIO_invariants001","Invariants generation already in progress.");
        defaultEnglish.put("GUIO_invariants002","Generator working");
        defaultEnglish.put("GUIO_mct001","Exporting net into CSV file failed.");
        defaultEnglish.put("GUIO_mct002","Write error");
        defaultEnglish.put("LOGentry00019","Starting MCT generator.");
        defaultEnglish.put("GUIO_mct003","Select MCT target path");
        defaultEnglish.put("GUIO_mct004","MCT file created");
        defaultEnglish.put("GUIO_mct005","Operation successful.");
        defaultEnglish.put("LOGentry00020","MCT file saved. Path:");
        defaultEnglish.put("GUIO_mct006","MCT file created");
        defaultEnglish.put("GUIO_mct007","File operation failed when creating MCT sets.");
        defaultEnglish.put("GUIO_mct008","MCT generator error");
        defaultEnglish.put("LOGentry00021","MCT generator failed:");
        defaultEnglish.put("LOGentry00022","Warning: unable to check if given clusters number (");
        defaultEnglish.put("LOGentry00023",") exceeds invariants number. If so, the procedure may fail.");
        defaultEnglish.put("GUIO_clusters001","Select CH metric directory");
        defaultEnglish.put("GUIO_clusters002","Use temporary directory");
        defaultEnglish.put("GUIO_clusters003","Multiple CH metric files can we written into default temporary directory (inadvised) or into\nthe selected one.");
        defaultEnglish.put("GUIO_clusters004","Directory selection");
        defaultEnglish.put("GUIO_clusters005","Select CH metric dir");
        defaultEnglish.put("GUIO_clusters006","Target directory for CH metric results");
        defaultEnglish.put("LOGentry00024","CH metric files will be put into the");
        defaultEnglish.put("LOGentry00025","Cluster files will be put into the");
        defaultEnglish.put("LOGentry00026","Cluster files will be put into the");
        defaultEnglish.put("LOGentry00027","Warning: Celinski-Harabasz metric computation in 32bit mode for large number of invariants can cause R/OS failure.");
        defaultEnglish.put("GUIO_clusters007","CH metric computation failed for");
        defaultEnglish.put("GUIO_clusters008"," clusters.\nPath:");
        defaultEnglish.put("LOGentry00028","Warning: unable to check if a given number of clusters (");
        defaultEnglish.put("LOGentry00029",") exceeds invariants number. If so, the procedure may fail.");
        defaultEnglish.put("GUIO_clusters009","Select cluster directory");
        defaultEnglish.put("GUIO_clusters009b","Use temporary directory");
        defaultEnglish.put("GUIO_clusters009c","Cancel operation");
        defaultEnglish.put("GUIO_clusters010","Multiple cluster files can we written into default temporary directory (not advised) or into\nthe selected one.");
        defaultEnglish.put("GUIO_clusters011","Select cluster dir");
        defaultEnglish.put("GUIO_clusters012","Target directory for cluster results");
        defaultEnglish.put("LOGentry00030","Cluster files will be put into the");
        defaultEnglish.put("GUIO_clusters013","Clustering generation failed for");
        defaultEnglish.put("GUIO_clusters014"," clusters.\nPath:");
        defaultEnglish.put("GUIO_csv001","CSV invariants file (.csv)");
        defaultEnglish.put("GUIO_csv002","Select CSV");
        defaultEnglish.put("GUIO_csv003","Select CSV file");
        defaultEnglish.put("GUIO_csv004","Select invariants file manually");
        defaultEnglish.put("GUIO_csv004b","Use computed invariants");
        defaultEnglish.put("LOGentry00031","Please select invariant file (.CSV) for the clustering manually or use invariants\nfrom the current network (they must be computed/loaded already!).");
        defaultEnglish.put("GUIO_inv001","Invariants source");
        defaultEnglish.put("GUIO_inv002","Exporting invariants into CSV file failed.\nCluster procedure cannot begin.");
        defaultEnglish.put("GUIO_inv003","CSV export error");
        defaultEnglish.put("GUIO_clusters015","Manually locate file");
        defaultEnglish.put("GUIO_clusters015b","Cancel procedure");
        defaultEnglish.put("GUIO_clusters016","No input.csv file in:\n");
        defaultEnglish.put("GUIO_clusters017","\nDo you want to select location manually?");
        defaultEnglish.put("GUIO_clusters018","No CSV invariants file");
        defaultEnglish.put("GUIO_clusters019","Select CSV invariants file");
        defaultEnglish.put("GUIO_clusters020","CSV invariants file:");
        defaultEnglish.put("GUIO_clusters021"," located. Starting single clustering procedure.");
        defaultEnglish.put("GUIO_clusters022","Starting MCT generator for file:");
        defaultEnglish.put("GUIO_clusters023","MCT generation (file) failed for:");
        defaultEnglish.put("LOGentry00032","R function failed for parameters:");
        defaultEnglish.put("LOGentry00032b","File name:");
        defaultEnglish.put("LOGentry00032c","Output dir:");
        defaultEnglish.put("LOGentry00032d","Algorithm:");
        defaultEnglish.put("LOGentry00032e","Metric:");
        defaultEnglish.put("LOGentry00032f","No. of clusters:");
        defaultEnglish.put("GUIO_clusters024","Clustering failed. Check log.");
        defaultEnglish.put("LOGentry00033","Unable to update simulator fields: (XTPN=");
        defaultEnglish.put("LOGentry00033b","; stepsValue=");
        defaultEnglish.put("LOGentry00033c","; stepsValue=");
        defaultEnglish.put("GUIO_fix001","Invisible arc: p");
        defaultEnglish.put("GUIO_fix002",". Removing...");
        defaultEnglish.put("GUIO_fix003","Invisible arc: t");
        defaultEnglish.put("GUIO_fix004","Arc list:");
        defaultEnglish.put("GUIO_fix005",", processed arcs:");
        defaultEnglish.put("GUIO_fix006",", removed ghost-arcs:");

        defaultEnglish.put("DM_menuFile","File");
        defaultEnglish.put("DM_menuFileDesc","The File Menu");
        defaultEnglish.put("DM_menuFileProject","New Project");
        defaultEnglish.put("DM_menuFileOpenProject","Open project...");
        defaultEnglish.put("DM_menuFileImportNet","Import network...");
        defaultEnglish.put("DM_menuFileMerge","Merge nets...");
        defaultEnglish.put("DM_menuFileSavePr","Save project...");
        defaultEnglish.put("DM_menuFileExport","Export network...");
        defaultEnglish.put("DM_menuFileExportPNT","Export as PNT...");
        defaultEnglish.put("DM_menuFileExportImg","Export to image...");
        defaultEnglish.put("DM_menuFileExportTex","Tex Export");
        defaultEnglish.put("DM_menuFileExportTexPT","Places and transitions table...");
        defaultEnglish.put("DM_menuFileExportTexInv","Invariants table...");
        defaultEnglish.put("DM_menuFileExportTexMCT","MCT table...");
        defaultEnglish.put("DM_menuFileExit","Exit");
        defaultEnglish.put("DM_menuFileExitQ1","Are you sure you want to close the program?");
        defaultEnglish.put("DM_menuFileExitQ2","Close Holmes");
        defaultEnglish.put("DM_menuView","View");
        defaultEnglish.put("DM_menuViewZoom100","Zoom 100%");
        defaultEnglish.put("DM_menuViewZoomIn","Increase zoom 10%");
        defaultEnglish.put("DM_menuViewZoomOut","Decrease zoom 10%");
        defaultEnglish.put("DM_menuWindows","Windows");
        defaultEnglish.put("DM_menuWindowsProject","Project");
        defaultEnglish.put("DM_menuWindowsConsole","Log Console");
        defaultEnglish.put("DM_menuWindowsProperties","Properties");
        defaultEnglish.put("DM_menuNetData","Net Data");
        defaultEnglish.put("DM_menuNetDataProperties","Net properties...");
        defaultEnglish.put("DM_menuNetDataSearch","Search node...");
        defaultEnglish.put("DM_menuNetDataTable","Net data tables...");
        defaultEnglish.put("DM_menuNetDataInvariants","Invariants Viewer...");
        defaultEnglish.put("DM_menuNetDataPStateM","Initial p-states manager...");
        defaultEnglish.put("DM_menuNetDataPStateMQ1","Net simulator must be stopped in order to access state manager.");
        defaultEnglish.put("DM_menuNetDataPStateMQ2","Simulator working");
        defaultEnglish.put("DM_menuNetDataSPNM","SPN firing rates manager...");
        defaultEnglish.put("DM_menuNetDataSSA","SSA p-states manager...");
        defaultEnglish.put("DM_menuSubnets","Subnets");
        defaultEnglish.put("DM_menuSubnetsCompr","Compress subnets");
        defaultEnglish.put("DM_menuSubnetsAlign","Align to upper left");
        defaultEnglish.put("DM_menuSubnetsResize","Resize panels");
        defaultEnglish.put("DM_menuSubnetsShowDet","Show details");
        defaultEnglish.put("DM_menuAnalysis","Analysis");
        defaultEnglish.put("DM_menuAnalysisInvariants","Invariants");
        defaultEnglish.put("DM_menuAnalysisInvGen","Invariants generator...");
        defaultEnglish.put("DM_menuAnalysisMCS","Minimal Cutting Sets...");
        defaultEnglish.put("DM_menuAnalysisKnockout","Knockout analysis...");
        defaultEnglish.put("DM_menuAnalysisClusters","Cluster analysis...");
        defaultEnglish.put("DM_menuAnalysisSim","Simulation");
        defaultEnglish.put("DM_menuAnalysisStateSim","State Simulator...");
        defaultEnglish.put("DM_menuAnalysisXTPNSim","XTPN Simulator...");
        defaultEnglish.put("DM_menuAnalysisNetDeco","Net decomposition");
        defaultEnglish.put("DM_menuAnalysisNetDecoA","Decomposition analysis...");
        defaultEnglish.put("DM_menuAnalysisNetDecoB","Branch analysis...");
        defaultEnglish.put("DM_menuAnalysisNetDecoC","Net comparison");
        defaultEnglish.put("DM_menuAnalysisNetDecoD","Graphlets");
        defaultEnglish.put("DM_menuAnalysisNetDecoE","Reduction");
        defaultEnglish.put("DM_menuOther","Other");
        defaultEnglish.put("DM_menuOtherMCT","MCT");
        defaultEnglish.put("DM_menuOtherMCTGen","Generate MCT Groups");
        defaultEnglish.put("DM_menuOtherMCTCre","Create simple MCT file");
        defaultEnglish.put("DM_menuOtherMCTFiles","MCT Files");
        defaultEnglish.put("DM_menuOtherMCTFilesA","MCT");
        defaultEnglish.put("DM_menuOtherInvGen","Invariants Simulation");
        defaultEnglish.put("DM_menuOtherFixArcs","FixArcs");
        defaultEnglish.put("DM_menuHelp","Help");
        defaultEnglish.put("DM_menuHelpAbout","About Holmes");

        //GUIReset:
        defaultEnglish.put("GUIR_reset001","Please stop simulation completely before continuing.");
        defaultEnglish.put("GUIR_reset002","Please stop XTPN simulation completely before continuing.");
        defaultEnglish.put("GUIR_reset003","Net has been changed since the last save. Continue and clear all data?");
        defaultEnglish.put("GUIR_reset004","Data clear warning");
        defaultEnglish.put("LOGentry00034","Net data deletion initiated.");
        defaultEnglish.put("LOGentry00035","Something went terribly wrong. Holmes emergency restart initiated.");
        defaultEnglish.put("GUIR_reset005","Net data deletion initiated.");
        defaultEnglish.put("LOGentry00036","t-invariants data removed from memory.");
        defaultEnglish.put("LOGentry00037","MCT data removed from memory.");
        defaultEnglish.put("LOGentry00038","p-invariants data removed from memory.");
        defaultEnglish.put("LOGentry00039","Clustering data removed from memory.");
        defaultEnglish.put("LOGentry00040","Decomposition data removed from memory.");

        //Toolbar:
        defaultEnglish.put("TB_toolTip001","LoopBack");
        defaultEnglish.put("TB_toolTip001d","Loop back to oldest action saved");
        defaultEnglish.put("TB_toolTip002","StepBack");
        defaultEnglish.put("TB_toolTip002d","Single action back simulation");
        defaultEnglish.put("TB_toolTip003","Loop");
        defaultEnglish.put("TB_toolTip003d","Loop simulation");
        defaultEnglish.put("TB_toolTip004","LoopSingleTrans");
        defaultEnglish.put("TB_toolTip004d","Loop single transition simulation");
        defaultEnglish.put("TB_toolTip005","Pause");
        defaultEnglish.put("TB_toolTip005d","Pause simulation");
        defaultEnglish.put("TB_toolTip006","Stop");
        defaultEnglish.put("TB_toolTip006d","Schedule a stop for the simulation");
        defaultEnglish.put("TB_toolTip007","SingleForward");
        defaultEnglish.put("TB_toolTip007d","Single transition forward simulation");
        defaultEnglish.put("TB_toolTip008","StepForward");
        defaultEnglish.put("TB_toolTip008d","Step forward simulation");
        defaultEnglish.put("TB_toolTip009","Reset");
        defaultEnglish.put("TB_toolTip009d","Reset simulator");
        defaultEnglish.put("TB_toolTip010","Ext.Net");
        defaultEnglish.put("TB_toolTip010d","Extend net elements");

        //PetriNetTools:
        defaultEnglish.put("PNTT_toolTipPointer","Allows to point at and move net components on the sheet.");
        defaultEnglish.put("PNTT_toolTipEraser","Allows to delete net components.");
        defaultEnglish.put("PNTT_toolTipPlace","Allows you to place a Place on the sheet.");
        defaultEnglish.put("PNTT_toolTipTrans","Allows you to place a Transition on the sheet.");
        defaultEnglish.put("PNTT_toolTipTPNTrans","Allows you to place a Time Transition on the sheet.");
        defaultEnglish.put("PNTT_toolTipSPNTrans","Allows you to place a Stochastic Transition on the sheet.");
        defaultEnglish.put("PNTT_toolTipSPNImmed","Allows you to place a Immediate Transition on the sheet.");
        defaultEnglish.put("PNTT_toolTipSPNDeter","Allows you to place a Deterministic Transition on the sheet.");
        defaultEnglish.put("PNTT_toolTipSPNSched","Allows you to place a Scheduled Transition on the sheet.");
        defaultEnglish.put("PNTT_toolTipArc","Allows you to place an Arc on the sheet.");
        defaultEnglish.put("PNTT_toolTipReadArc","Allows you to place an Readarc on the sheet.");
        defaultEnglish.put("PNTT_toolTipInhibArc","Allows you to place an Inhibitor Arc on the sheet.");
        defaultEnglish.put("PNTT_toolTipResetArc","Allows you to place a Reset Arc on the sheet.");
        defaultEnglish.put("PNTT_toolTipEquArc","Allows you to place an Equal Arc on the sheet.");
        defaultEnglish.put("PNTT_toolTipModArc","Allows you to place an Modifier Arc on the sheet.");
        defaultEnglish.put("PNTT_toolTipXTPNplace","xTPN place with time range.");
        defaultEnglish.put("PNTT_toolTipXTPNtrans","xTPN transition with TPN and DPN-like time ranges.");
        defaultEnglish.put("PNTT_toolTipXTPNarc","xTPN new arc");
        defaultEnglish.put("PNTT_toolTipXTPNinhArc","xTPN new inhibitor arc");
        defaultEnglish.put("PNTT_toolTipSubnetP","Allows you to create subnet with place-interfaces.");
        defaultEnglish.put("PNTT_toolTipSubnetT","Allows you to create subnet with transition-interfaces.");
        defaultEnglish.put("PNTT_toolTipSubnetPT","Allows you to create subnet with P/T interfaces.");
        defaultEnglish.put("PNTT_toolTipCplace","Allows you to create colored place.");
        defaultEnglish.put("PNTT_toolTipCtrans","Allows you to create colored transition.");
        defaultEnglish.put("PNTT_toolTipCarc","Allows you to create arc for colored net.");

        //SharedActionsXTPN:
        defaultEnglish.put("SAXTPN_entry001","Input or output XTPN transitions cannot be immediate. This transition\nis not in Beta-mode or Beta time values are zero. Change impossible.");
        defaultEnglish.put("SAXTPN_entry001t","Immediate int/out XTPN transitions problem");
        defaultEnglish.put("SAXTPN_entry002","Input or output XTPN transitions cannot be immediate. This transition\nis not in Alfa-mode and Beta time values are zero. Change impossible.");
        defaultEnglish.put("SAXTPN_entry002t","Immediate int/out XTPN transitions problem");
        defaultEnglish.put("SAXTPN_entry003","Reduce XTPN transition into classical one? This can reset\ncurrent time values assigned to Alfa/Beta ranges.");
        defaultEnglish.put("SAXTPN_entry003t","XTPN transition reduction");
        defaultEnglish.put("SAXTPN_entry004opt1","Reduce to classical place");
        defaultEnglish.put("SAXTPN_entry004opt2","Stay as XTPN");
        defaultEnglish.put("SAXTPN_entry004_1","Turning γ-mode off will clear all times of tokens (");
        defaultEnglish.put("SAXTPN_entry004_2",") and \nas a result place will have classical PN features.\nTransform XTPN place into classical place?");
        defaultEnglish.put("SAXTPN_entry004t","Transformation into classical place");
        defaultEnglish.put("SAXTPN_entry005opt1","Transform into XTPN");
        defaultEnglish.put("SAXTPN_entry005opt2","Stay as classical PN place");
        defaultEnglish.put("SAXTPN_entry005_1","This will transform classical PN place into XTPN.\nAll tokens (");
        defaultEnglish.put("SAXTPN_entry005_2",") will be assigned 0.0 time values.\nTransform into XTPN place?");
        defaultEnglish.put("SAXTPN_entry005t","Conversion into XTPN place");
        defaultEnglish.put("SAXTPN_entry006opt1","▲ Increase α-max to ");
        defaultEnglish.put("SAXTPN_entry006opt1b","▼ Decrease α-min to ");
        defaultEnglish.put("SAXTPN_entry006opt2","❌ Cancel");
        defaultEnglish.put("SAXTPN_entry006_1","Proposed value α-min = ");
        defaultEnglish.put("SAXTPN_entry006_2"," cannot be higher than current α-max = ");
        defaultEnglish.put("SAXTPN_entry006_3","\nIncrease old α-max (default action) or decrease new α-min?");
        defaultEnglish.put("SAXTPN_entry006t","Alpha range problem: α-minimum too high");
        defaultEnglish.put("SAXTPN_entry007","Input or output XTPN transitions cannot be immediate. Alternatively\nturn off both Alfa and Beta modes for a classical immediate transition.");
        defaultEnglish.put("SAXTPN_entry007t","Immediate int/out XTPN transitions problem");
        defaultEnglish.put("SAXTPN_entry007op1","▲ Increase α-max to ");
        defaultEnglish.put("SAXTPN_entry007op2","▼ Decrease α-min ");
        defaultEnglish.put("SAXTPN_entry007op3","❌ Cancel");
        defaultEnglish.put("SAXTPN_entry007_1","Proposed value α-max = ");
        defaultEnglish.put("SAXTPN_entry007_1b"," cannot be lower than current α-min = ");
        defaultEnglish.put("SAXTPN_entry007_1c","\nIncrease new α-max or decrease old α-min (default action)?");
        defaultEnglish.put("SAXTPN_entry007t2","Alpha range problem: α-maximum too low");
        defaultEnglish.put("SAXTPN_entry008opt1","▲ Increase β-max to ");
        defaultEnglish.put("SAXTPN_entry008opt2","▼ Decrease β-min to ");
        defaultEnglish.put("SAXTPN_entry008opt3","❌ Cancel");
        defaultEnglish.put("SAXTPN_entry008_1","Proposed value β-min = ");
        defaultEnglish.put("SAXTPN_entry008_2"," cannot be higher than current β-max = ");
        defaultEnglish.put("SAXTPN_entry008_3","Increase old betaMaximum (default action) or decrease new betaMinimum?");
        defaultEnglish.put("SAXTPN_entry008t","Beta range problem: β-minimum too high");
        defaultEnglish.put("SAXTPN_entry009","Input or output XTPN transitions cannot be immediate. Alternatively\nturn off both Alfa and Beta modes for a classical immediate transition.");
        defaultEnglish.put("SAXTPN_entry009t","Immediate int/out XTPN transitions problem");
        defaultEnglish.put("SAXTPN_entry009op1","▲ Increase β-max to ");
        defaultEnglish.put("SAXTPN_entry009op2","▼ Decrease β-min to ");
        defaultEnglish.put("SAXTPN_entry009op3","❌ Cancel");
        defaultEnglish.put("SAXTPN_entry009_1","Proposed value β-max = ");
        defaultEnglish.put("SAXTPN_entry009_1b","cannot be lower than current β-min = ");
        defaultEnglish.put("SAXTPN_entry009_1c","Increase new β-max or decrease old β-min (default action)?");
        defaultEnglish.put("SAXTPN_entry009t2","Beta range problem: β-maximum too low");
        defaultEnglish.put("SAXTPN_entry010op1","▲ Increase γ-max to ");
        defaultEnglish.put("SAXTPN_entry010op2","▼ Decrease γ-min to ");
        defaultEnglish.put("SAXTPN_entry010op3","❌ Cancel");
        defaultEnglish.put("SAXTPN_entry010_1","Proposed value γ-min = ");
        defaultEnglish.put("SAXTPN_entry010_2","cannot be higher than current γ-max = ");
        defaultEnglish.put("SAXTPN_entry010_3","Increase current γ-max (default action) or decrease proposed γ-min?");
        defaultEnglish.put("SAXTPN_entry010t","Gamma range problem: γ-minimum too high");
        defaultEnglish.put("SAXTPN_entry011op1","▲ Increase γ-max to ");
        defaultEnglish.put("SAXTPN_entry011op2","▼ Decrease γ-min to ");
        defaultEnglish.put("SAXTPN_entry011op3","❌ Cancel");
        defaultEnglish.put("SAXTPN_entry011_1","Proposed value γ-max = ");
        defaultEnglish.put("SAXTPN_entry011_2","cannot be lower than current γ-min = ");
        defaultEnglish.put("SAXTPN_entry011_3","Increase proposed γ-max or decrease current γ-min (default action)?");
        defaultEnglish.put("SAXTPN_entry011t","Gamma range problem: γ-maximum too low");

        //SelectionPanel:
        defaultEnglish.put("SP_toolTip001","No elements selected.");

        //HolmesDockWindowsTable:
        defaultEnglish.put("HDWT_entry001","Mode:");
        defaultEnglish.put("HDWT_entry001op1","XTPN simulator");
        defaultEnglish.put("HDWT_entry001op2","PN simulators");
        defaultEnglish.put("HDWT_dialog001","XTPN simulator must be stopped first.");
        defaultEnglish.put("HDWT_dialog001t","XTPN Simulator working");
        defaultEnglish.put("HDWT_dialog002","PN simulator must be stopped first.");
        defaultEnglish.put("HDWT_dialog002t","PN Simulator working");
        defaultEnglish.put("LOGentry00041","Error while changing graphical simulator mode.");
        defaultEnglish.put("HDWT_entry002PNsim","Time/step:");
        defaultEnglish.put("HDWT_entry003PNsim","Simulation options:");
        defaultEnglish.put("HDWT_entry004PNsim","Loop simulation");
        defaultEnglish.put("HDWT_entry005PNsim","Loop single transition simulation");
        defaultEnglish.put("HDWT_entry006PNsim","Pause simulation");
        defaultEnglish.put("HDWT_entry007PNsim","Schedule a stop for the simulation");
        defaultEnglish.put("HDWT_entry008PNsim","Reset all tokens in places.");
        defaultEnglish.put("HDWT_entry009PNsim","Save m0 state.");
        defaultEnglish.put("LOGentry00042","Operation impossible while simulator is working.");
        defaultEnglish.put("LOGentry00043","Operation impossible while XTPN simulator is working.");
        defaultEnglish.put("HDWT_entry010op1","Save new m0 state");
        defaultEnglish.put("HDWT_entry010msg1","Add new net state to states table?");
        defaultEnglish.put("HDWT_entry010t","Saving m0 state");
        defaultEnglish.put("HDWT_entry011PNsim","Other modes:");
        defaultEnglish.put("HDWT_entry012PNsim","One action back");
        defaultEnglish.put("HDWT_entry013PNsim","One transition forward");
        defaultEnglish.put("HDWT_entry014PNsim","Loop back to oldest saved action");
        defaultEnglish.put("HDWT_entry015PNsim","One step forward");
        defaultEnglish.put("HDWT_entry016PNsim","Reset all color tokens in places.");
        defaultEnglish.put("HDWT_entry017PNsim","Reset all color tokens in places.");
        defaultEnglish.put("HDWT_entry017PNsim_1","Color PN (experimental) simulator - highly unstable.");
        defaultEnglish.put("HDWT_entry017PNsim_2","Module under construction");
        defaultEnglish.put("HDWT_entry018PNsim","Open states manager window.");
        defaultEnglish.put("HDWT_entry018PNsim_1","Net simulator must be stopped in order to access state manager.");
        defaultEnglish.put("HDWT_entry018PNsim_1t","Simulator working");
        defaultEnglish.put("HDWT_entry019PNsim","Maximum mode");
        defaultEnglish.put("HDWT_entry019PNsim_1","Mode overrided by an active single mode.");
        defaultEnglish.put("HDWT_entry019PNsim_1t","Cannot change now");
        defaultEnglish.put("HDWT_entry020PNsim","Single mode");
        defaultEnglish.put("HDWT_entry021XTPNsim","Step:");
        defaultEnglish.put("HDWT_entry022XTPNsim","Time:");
        defaultEnglish.put("HDWT_entry023XTPNsim","Simulation buttons:");
        defaultEnglish.put("HDWT_entry024XTPNsim","Loop simulation");
        defaultEnglish.put("HDWT_entry024XTPNsim_1","Holmes simulator is running. Please wait or stop it manually first.");
        defaultEnglish.put("HDWT_entry024XTPNsim_1t","Simulator working");
        defaultEnglish.put("HDWT_entry025XTPNsim","Pause simulation");
        defaultEnglish.put("HDWT_entry026XTPNsim","Schedule a stop for the simulation");
        defaultEnglish.put("HDWT_entry027XTPNsim","Reset all tokens in places.");
        defaultEnglish.put("HDWT_entry028XTPNsim","Reset all tokens in places.");
        defaultEnglish.put("HDWT_entry028XTPNsim_op1","Replace XTPN state");
        defaultEnglish.put("HDWT_entry028XTPNsim_1","Replace first p-state vector with the current net state?");
        defaultEnglish.put("HDWT_entry028XTPNsim_1t","Replace XTPN state");
        defaultEnglish.put("HDWT_entry029XTPNsim","Firing delay:");
        defaultEnglish.put("HDWT_entry030XTPNsim","Time values visibility:");
        defaultEnglish.put("HDWT_entry031XTPNsim","Switch alpha visibility.");
        defaultEnglish.put("HDWT_entry032XTPNsim","Switch beta visibility.");
        defaultEnglish.put("HDWT_entry033XTPNsim","Switch gamma visibility.");
        defaultEnglish.put("HDWT_entry034XTPNsim","Switch tau visibility.");
        defaultEnglish.put("HDWT_entry035XTPNsim","Fast simulation options:");
        defaultEnglish.put("HDWT_entry036XTPNsim","Compute steps from zero marking through the number of states");
        defaultEnglish.put("HDWT_entry036XTPNsim_1","Holmes simulator is running. Please wait or stop it manually first.");
        defaultEnglish.put("HDWT_entry036XTPNsim_1t","Simulator working");
        defaultEnglish.put("HDWT_entry037XTPNsim","Steps");
        defaultEnglish.put("HDWT_entry038XTPNsim","Time");
        defaultEnglish.put("HDWT_entry039XTPNsim","Rep.:");
        defaultEnglish.put("HDWT_entry040XTPNsim","Knockout simulation");
        defaultEnglish.put("HDWT_entry041XTPNsim","Compute steps from zero marking through the number of states");
        defaultEnglish.put("HDWT_entry041XTPNsim_1","Holmes simulator is running. Please wait or stop it manually first.");
        defaultEnglish.put("HDWT_entry041XTPNsim_1t","Simulator working");
        defaultEnglish.put("HDWT_entry042place","Name");
        defaultEnglish.put("HDWT_entry043place","Comment:");
        defaultEnglish.put("HDWT_entry044place","Tokens:");
        defaultEnglish.put("LOGentry00044","Negative number of tokens in");
        defaultEnglish.put("HDWT_entry045place","Sheet:");
        defaultEnglish.put("HDWT_entry046place","Zoom:");
        defaultEnglish.put("HDWT_entry047place","Portal:");
        defaultEnglish.put("HDWT_entry047place_1","Place contains more than one location!");
        defaultEnglish.put("HDWT_entry048place","Location:");
        defaultEnglish.put("HDWT_entry049place","Name offset:");
        defaultEnglish.put("HDWT_entry050place","MouseWheel - up/down ; SHIFT+MouseWheel - left/right");
        defaultEnglish.put("HDWT_entry051place","T0 Red:");
        defaultEnglish.put("LOGentry00045","Negative number of tokens in ");
        defaultEnglish.put("HDWT_entry052place","T3 Yellow:");
        defaultEnglish.put("HDWT_entry053place","T1 Green:");
        defaultEnglish.put("HDWT_entry054place","T4 Grey:");
        defaultEnglish.put("HDWT_entry055place","T2 Blue:");
        defaultEnglish.put("HDWT_entry056place","T5 Black:");
        defaultEnglish.put("HDWT_entry057XTPNplace","Name:");
        defaultEnglish.put("HDWT_entry058XTPNplace","Comment:");
        defaultEnglish.put("HDWT_entry059XTPNplace","XTPN mode:");
        defaultEnglish.put("HDWT_entry060XTPNplaceG_ON","<html><center>Gamma<br>ON</center></html>");
        defaultEnglish.put("HDWT_entry060XTPNplaceG_OFF","<html><center>Gamma<br>OFF</center></html>");
        defaultEnglish.put("HDWT_entry061XTPNplaceG_vis","<html><center>Gamma<br>visible</center></html>");
        defaultEnglish.put("HDWT_entry061XTPNplaceG_invis","<html><center>Gamma<br>hidden</center><html>");
        defaultEnglish.put("HDWT_entry062XTPNplaceG_off","<html><center>Gamma<br>offset</center></html>");
        defaultEnglish.put("HDWT_entry063XTPNplaceG_changeLoc","<html><center>Change<br>location</center><html>");
        defaultEnglish.put("HDWT_entry064XTPNplaceG","MouseWheel - up/down ; SHIFT+MouseWheel - left/right");
        defaultEnglish.put("HDWT_entry065XTPNplaceG","γ (min/max):");
        defaultEnglish.put("HDWT_entry066XTPNplaceG","Tokens in place:");
        defaultEnglish.put("HDWT_entry067XTPNplaceG","Fraction:");
        defaultEnglish.put("HDWT_entry068XTPNplaceName_OFF","<html><center>Name<br>offset</center><html>");
        defaultEnglish.put("HDWT_entry069XTPNplaceName","MouseWheel - up/down ; SHIFT+MouseWheel - left/right");
        defaultEnglish.put("HDWT_entry070XTPNplaceName_changeLoc","<html><center>Change<br>location</center><html>");
        defaultEnglish.put("HDWT_entry071XTPNplaceTokens","<html>Tokens<br>window</html>");
        defaultEnglish.put("HDWT_entry072XTPNplaceTokens","<html><center>Add<br>0-token</center></html>");
        defaultEnglish.put("HDWT_entry073XTPNplaceTokens","<html>Add<br>0-token</html>");
        defaultEnglish.put("HDWT_entry074XTPNplaceTokens","<html>Add<br>token</html>");
        defaultEnglish.put("HDWT_entry075XTPNplaceTokens","<html><center>Remove<br>0-token</center></html>");
        defaultEnglish.put("HDWT_entry076XTPNplaceTokens","<html>Remove<br>0-token</html>");
        defaultEnglish.put("HDWT_entry077XTPNplaceTokens","<html>Remove<br>token</html>");
        defaultEnglish.put("HDWT_entry078XTPNplace","Sheet:");
        defaultEnglish.put("HDWT_entry079XTPNplace","Zoom:");
        defaultEnglish.put("HDWT_entry080XTPNplace","Portal:");
        defaultEnglish.put("HDWT_entry080XTPNplace_1","Place contains more than one location!");
        defaultEnglish.put("HDWT_entry080XTPNplace_1t","Cannot proceed");
        defaultEnglish.put("HDWT_entry081XTPNplace","Location:");
        defaultEnglish.put("HDWT_entry082XTPNplace","Name offset:");
        defaultEnglish.put("HDWT_entry083XTPNplace","<html><center>Name<br>offset</center><html>");
        defaultEnglish.put("HDWT_entry084XTPNplace","MouseWheel - up/down ; SHIFT+MouseWheel - left/right");
        defaultEnglish.put("HDWT_entry085XTPNplace","<html><center>Change<br>location</center><html>");
        defaultEnglish.put("HDWT_entry086trans","Name:");
        defaultEnglish.put("HDWT_entry087trans","Comment:");
        defaultEnglish.put("HDWT_entry088trans","Trans. Type:");
        defaultEnglish.put("HDWT_entry089trans","Sheet:");
        defaultEnglish.put("HDWT_entry090trans","Zoom:");
        defaultEnglish.put("HDWT_entry091trans","Location:");
        defaultEnglish.put("HDWT_entry092trans","Portal:");
        defaultEnglish.put("HDWT_entry092trans_1","Transition contains more than one location!");
        defaultEnglish.put("HDWT_entry092trans_1t","Cannot proceed");
        defaultEnglish.put("HDWT_entry093trans","Functional:");
        defaultEnglish.put("HDWT_entry094trans","<html>Functions<br>&nbsp;&nbsp;&nbsp;editor&nbsp;</html>");
        defaultEnglish.put("HDWT_entry095trans","Name offset:");
        defaultEnglish.put("HDWT_entry096trans","MouseWheel - up/down ; SHIFT+MouseWheel - left/right");
        defaultEnglish.put("HDWT_entry097Ctrans","Colored transition data:");
        defaultEnglish.put("HDWT_entry098Ctrans","Name:");
        defaultEnglish.put("HDWT_entry099Ctrans","Comment:");
        defaultEnglish.put("HDWT_entry100Ctrans","Sheet:");
        defaultEnglish.put("HDWT_entry101Ctrans","Zoom:");
        defaultEnglish.put("HDWT_entry102Ctrans","Portal:");
        defaultEnglish.put("HDWT_entry102Ctrans_1","Transition contains more than one location!");
        defaultEnglish.put("HDWT_entry102Ctrans_1t","Cannot proceed");
        defaultEnglish.put("HDWT_entry103Ctrans","Location:");
        defaultEnglish.put("HDWT_entry104Ctrans","Name offset:");
        defaultEnglish.put("HDWT_entry105Ctrans","MouseWheel - up/down ; SHIFT+MouseWheel - left/right");
        defaultEnglish.put("HDWT_entry106Ctrans","Required tokens threshold:");
        defaultEnglish.put("HDWT_entry107Ctrans","T0 red:");
        defaultEnglish.put("HDWT_entry108Ctrans","T3 yellow:");
        defaultEnglish.put("HDWT_entry109Ctrans","T1 green:");
        defaultEnglish.put("HDWT_entry110Ctrans","T4 grey:");
        defaultEnglish.put("HDWT_entry111Ctrans","T2 blue:");
        defaultEnglish.put("HDWT_entry112Ctrans","T5 black:");
        defaultEnglish.put("HDWT_entry113SPNtrans","Name:");
        defaultEnglish.put("HDWT_entry114SPNtrans","Comment:");
        defaultEnglish.put("HDWT_entry115SPNtrans","Trans. Type:");
        defaultEnglish.put("HDWT_entry116SPNtrans","Firing rate:");
        defaultEnglish.put("HDWT_entry117SPNtrans","Sheet:");
        defaultEnglish.put("HDWT_entry118SPNtrans","Zoom:");
        defaultEnglish.put("HDWT_entry119SPNtrans","Location:");
        defaultEnglish.put("HDWT_entry120SPNtrans","Portal:");
        defaultEnglish.put("HDWT_entry120SPNtrans_1","Transition contains more than one location!");
        defaultEnglish.put("HDWT_entry120SPNtrans_1t","Cannot proceed");
        defaultEnglish.put("HDWT_entry121SPNtrans","Functional:");
        defaultEnglish.put("HDWT_entry122SPNtrans","<html>Functions<br>&nbsp;&nbsp;&nbsp;editor&nbsp;</html>");
        defaultEnglish.put("HDWT_entry123SPNtrans","Name offset:");
        defaultEnglish.put("HDWT_entry124SPNtrans","MouseWheel - up/down ; SHIFT+MouseWheel - left/right");
        defaultEnglish.put("HDWT_entry125TPNtrans","Name:");
        defaultEnglish.put("HDWT_entry126TPNtrans","Comment:");
        defaultEnglish.put("HDWT_entry127TPNtrans","Trans. Type:");
        defaultEnglish.put("HDWT_entry128TPNtrans","Duration:");
        defaultEnglish.put("HDWT_entry129TPNtrans","TPN active");
        defaultEnglish.put("HDWT_entry130TPNtrans","DPN active");
        defaultEnglish.put("HDWT_entry131TPNtrans","Sheet:");
        defaultEnglish.put("HDWT_entry132TPNtrans","Zoom:");
        defaultEnglish.put("HDWT_entry133TPNtrans","Location:");
        defaultEnglish.put("HDWT_entry134TPNtrans","Portal:");
        defaultEnglish.put("HDWT_entry134TPNtrans_1","Transition contains more than one location!");
        defaultEnglish.put("HDWT_entry134TPNtrans_1t","Cannot proceed");
        defaultEnglish.put("HDWT_entry135TPNtrans","Functional:");
        defaultEnglish.put("HDWT_entry136TPNtrans","<html>Functions<br>&nbsp;&nbsp;&nbsp;editor&nbsp;</html>");
        defaultEnglish.put("HDWT_entry137TPNtrans","Name offset:");
        defaultEnglish.put("HDWT_entry138TPNtrans","MouseWheel - up/down ; SHIFT+MouseWheel - left/right");
        defaultEnglish.put("HDWT_entry139XTPNtrans","Name:");
        defaultEnglish.put("HDWT_entry140XTPNtrans","Comment:");
        defaultEnglish.put("HDWT_entry141XTPNtrans","Time mode:");
        defaultEnglish.put("HDWT_entry142XTPNtransA_ON","<html><center>Alpha:<br>ON</center></html>");
        defaultEnglish.put("HDWT_entry142XTPNtransA_OFF","<html><center>Alpha:<br>OFF</center></html>");
        defaultEnglish.put("HDWT_entry143XTPNtransB_ON","<html><center>Beta:<br>ON</center></html>");
        defaultEnglish.put("HDWT_entry143XTPNtransB_OFF","<html><center>Beta:<br>OFF</center></html>");
        defaultEnglish.put("HDWT_entry144XTPNtrans","<html><center>XTPN</center></html>");
        defaultEnglish.put("HDWT_entry145XTPNtransA_vis","<html>α:visible<html>");
        defaultEnglish.put("HDWT_entry145XTPNtransA_invis","<html>α:hidden<html>");
        defaultEnglish.put("HDWT_entry146XTPNtransB_vis","<html>β:visible</html>");
        defaultEnglish.put("HDWT_entry146XTPNtransB_invis","<html>β:hidden</html>");
        defaultEnglish.put("HDWT_entry147XTPNtransT_vis","<html>τ:visible</html>");
        defaultEnglish.put("HDWT_entry147XTPNtransT_invis","<html>τ:hidden<html>");
        defaultEnglish.put("HDWT_entry148XTPNtransA_off","<html><center>Alpha<br>offset</center><html>");
        defaultEnglish.put("HDWT_entry149XTPNtransB_changeLoc","<html><center>Change<br>location</center><html>");
        defaultEnglish.put("HDWT_entry150XTPNtrans","MouseWheel - up/down ; SHIFT+MouseWheel - left/right");
        defaultEnglish.put("HDWT_entry151XTPNtransB_off","<html><center>Beta<br>offset</center><html>");
        defaultEnglish.put("HDWT_entry152XTPNtransB_changeLoc","<html><center>Change<br>location</center><html>");
        defaultEnglish.put("HDWT_entry153XTPNtransB","MouseWheel - up/down ; SHIFT+MouseWheel - left/right");
        defaultEnglish.put("HDWT_entry154XTPNtransB_off","<html><center>Beta<br>offset</center><html>");
        defaultEnglish.put("HDWT_entry155XTPNtransT_off","<html><center>Tau<br>offset</center><html>");
        defaultEnglish.put("HDWT_entry156XTPNtransT_changeLoc","<html><center>Change<br>location</center><html>");
        defaultEnglish.put("HDWT_entry157XTPNtransT","MouseWheel - up/down ; SHIFT+MouseWheel - left/right");
        defaultEnglish.put("HDWT_entry158XTPNtrans","α (min/max): ");
        defaultEnglish.put("HDWT_entry159XTPNtrans","β (min/max): ");
        defaultEnglish.put("HDWT_entry160XTPNtrans","Mass-Action kinetics");
        defaultEnglish.put("HDWT_entry161XTPNtrans","Immediate");
        defaultEnglish.put("HDWT_entry162XTPNtrans","Functional");
        defaultEnglish.put("HDWT_entry163XTPNtrans","<html>Functions<br>&nbsp;&nbsp;&nbsp;editor&nbsp;</html>");
        defaultEnglish.put("HDWT_entry164XTPNtrans","Portal:");
        defaultEnglish.put("HDWT_entry164XTPNtrans_1","XTPN Transition contains more than one location!");
        defaultEnglish.put("HDWT_entry164XTPNtrans_1t","Cannot proceed");
        defaultEnglish.put("HDWT_entry165XTPNtrans","Fraction:");
        defaultEnglish.put("HDWT_entry166XTPNtrans","Sheet:");
        defaultEnglish.put("HDWT_entry167XTPNtrans","Zoom:");
        defaultEnglish.put("HDWT_entry168XTPNtrans","Location:");
        defaultEnglish.put("HDWT_entry169XTPNtrans","Name offset:");
        defaultEnglish.put("HDWT_entry170XTPNtransName_off","<html><center>Name<br>offset</center><html>");
        defaultEnglish.put("HDWT_entry171XTPNtransName","MouseWheel - up/down ; SHIFT+MouseWheel - left/right");
        defaultEnglish.put("HDWT_entry172XTPNtransName_changeLoc","<html><center>Change<br>location</center><html>");
        defaultEnglish.put("HDWT_entry173subnet","Subnet(sheet):");
        defaultEnglish.put("HDWT_entry174subnet","Name:");
        defaultEnglish.put("HDWT_entry175subnet","Comment:");
        defaultEnglish.put("HDWT_entry176subnet","Subnet T-type");
        defaultEnglish.put("HDWT_entry177subnet","Subnet P-type");
        defaultEnglish.put("HDWT_entry178subnet","Sheet:");
        defaultEnglish.put("HDWT_entry179subnet","Zoom:");
        defaultEnglish.put("HDWT_entry180subnet","Location:");
        defaultEnglish.put("HDWT_entry181subnet","Name offset:");
        defaultEnglish.put("HDWT_entry182subnet","MouseWheel - up/down ; SHIFT+MouseWheel - left/right");
        defaultEnglish.put("HDWT_entry183arc","Comment:");
        defaultEnglish.put("HDWT_entry184arc","Weight (");
        defaultEnglish.put("HDWT_entry185arc","Weight:");
        defaultEnglish.put("HDWT_entry186arc","Type:");
        defaultEnglish.put("HDWT_entry187arc","Read arc:");
        defaultEnglish.put("HDWT_entry188arc","no");
        defaultEnglish.put("HDWT_entry189arc","yes [paired arc ID:");
        defaultEnglish.put("HDWT_entry190arc","double arc (hidden readarc)");
        defaultEnglish.put("HDWT_entry191arc","Start Node name:");
        defaultEnglish.put("HDWT_entry192arc","Sheet:");
        defaultEnglish.put("HDWT_entry193arc","Location:");
        defaultEnglish.put("HDWT_entry194arc","End Node name:");
        defaultEnglish.put("HDWT_entry195arc","Sheet:");
        defaultEnglish.put("HDWT_entry196arc","Location:");
        defaultEnglish.put("HDWT_entry197arc","T-->P (Transition to Place weights):");
        defaultEnglish.put("HDWT_entry198arc","P-->T (Place to Transition weights):");
        defaultEnglish.put("HDWT_entry199arc","W0 (red):");
        defaultEnglish.put("HDWT_entry200arc","W3 (yellow):");
        defaultEnglish.put("HDWT_entry201arc","W1 (green):");
        defaultEnglish.put("HDWT_entry202arc","W4 (grey):");
        defaultEnglish.put("HDWT_entry203arc","W2 (blue):");
        defaultEnglish.put("HDWT_entry204arc","W5 (black):");
        defaultEnglish.put("HDWT_entry205sheet","Project type:");
        defaultEnglish.put("HDWT_entry206sheet","Petri net (normal)");
        defaultEnglish.put("HDWT_entry207sheet","PN Name:");
        defaultEnglish.put("HDWT_entry208sheet","(sheet position:");
        defaultEnglish.put("HDWT_entry209sheet","Zoom:");
        defaultEnglish.put("HDWT_entry210sheet","Width:");
        defaultEnglish.put("HDWT_entry211sheet","Height:");
        defaultEnglish.put("HDWT_entry212sheet","Autoscroll:");
        defaultEnglish.put("HDWT_entry213TinvPanel","T-invariant:");
        defaultEnglish.put("HDWT_entry214TinvPanel","null transitions");
        defaultEnglish.put("HDWT_entry215TinvPanel","inv/trans frequency");
        defaultEnglish.put("LOGentry00046error","Error (1000001): createT_invSubWindow");
        defaultEnglish.put("HDWT_entry216TinvPanel","Previous");
        defaultEnglish.put("HDWT_entry217TinvPanel","Show previous invariant data.");
        defaultEnglish.put("HDWT_entry218TinvPanel","<html>&nbsp;&nbsp;&nbsp;Next&nbsp;</html>");
        defaultEnglish.put("HDWT_entry219TinvPanel","Show next invariant data.");
        defaultEnglish.put("HDWT_entry220TinvPanel","Refresh");
        defaultEnglish.put("HDWT_entry220TinvPanel_1","If t-inv types have been determined, this button will refresh the content of the three comboboxes below:");
        defaultEnglish.put("HDWT_entry221TinvPanel","Recalculate");
        defaultEnglish.put("HDWT_entry221TinvPanel_1","This will force the program to determine the type of t-invariants (it may take time) and refresh the comboboxes below:");
        defaultEnglish.put("HDWT_entry222TinvPanel","<html>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Show<br>&nbsp;&nbsp;&nbsp;&nbsp;details</html>");
        defaultEnglish.put("HDWT_entry223TinvPanel","Color MCT");
        defaultEnglish.put("HDWT_entry224TinvPanel","Transitions glow");
        defaultEnglish.put("HDWT_entry225TinvPanel","Invariant-net structure painted");
        defaultEnglish.put("HDWT_entry226TinvPanel","Min. time: ");
        defaultEnglish.put("HDWT_entry227TinvPanel","Max. time:");
        defaultEnglish.put("HDWT_entry228TinvPanel","Avg. time:");
        defaultEnglish.put("HDWT_entry229TinvPanel","Structure:");
        defaultEnglish.put("HDWT_entry230TinvPanel","(size:");
        defaultEnglish.put("LOGentry00047","Critical error in t-invariants subwindow.\nT-invariants size differ from transition set cardinality!");
        defaultEnglish.put("LOGentry00048","Transitions not covered by t-invariants:");
        defaultEnglish.put("LOGentry00049","(IMPORTANT: only real, canonical t-invariants (Cx=0) were used for coverage evaluation!)");
        defaultEnglish.put("HDWT_entry231TinvPanel","t-invariants data unavailable.");
        defaultEnglish.put("HDWT_entry231TinvPanel_t","No t-invariants");
        defaultEnglish.put("HDWT_entry232PinvPanel","p-invariant:");
        defaultEnglish.put("HDWT_entry233PinvPanel","null places");
        defaultEnglish.put("HDWT_entry234PinvPanel","inv/place frequency");
        defaultEnglish.put("HDWT_entry235PinvPanel","<html>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Show<br>&nbsp;&nbsp;&nbsp;&nbsp;details</html>");
        defaultEnglish.put("LOGentry00050error","Error (1000003) : probably not implemented features for p-invariants in the t-invariants code window.");
        defaultEnglish.put("LOGentry00051","Critical error in p-invariants subwindow.\np-invariants size differ from transition set cardinality!");
        defaultEnglish.put("HWDT_entry236","p-invariants data unavailable.");
        defaultEnglish.put("HDWT_entry236_t","No p-invariants");
        defaultEnglish.put("HDWT_entry237PinvPanel","Places not covered by p-invariants:");
        defaultEnglish.put("HDWT_entry237PinvPanel_1","p-invariants data unavailable.");
        defaultEnglish.put("HDWT_entry237PinvPanel_1t","No p-invariants");
        defaultEnglish.put("HDWT_entry238PinvPanel","(size: ");
        defaultEnglish.put("HDWT_entry239MCTPanel","Choose MCT:");
        defaultEnglish.put("HDWT_entry240MCTPanel","<html>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Show<br>&nbsp;&nbsp;&nbsp;&nbsp;details</html>");
        defaultEnglish.put("HDWT_entry241MCTPanel","Different colors");
        defaultEnglish.put("HDWT_entry242MCTPanel","(size:");
        defaultEnglish.put("HDWT_entry243MCTPanel","No-MCT transitions");
        defaultEnglish.put("HDWT_entry244MCTPanel","Show all");
        defaultEnglish.put("HDWT_entry245MCTPanel","Trivial MCT-transitions (");
        defaultEnglish.put("HDWT_entry246MCTPanel","Transitions (");
        defaultEnglish.put("HDWT_entry247MCTPanel",") of MCT #");
        defaultEnglish.put("HDWT_entry248ClusterPanel","Algorithm:");
        defaultEnglish.put("HDWT_entry249ClusterPanel","Metric:");
        defaultEnglish.put("HDWT_entry250ClusterPanel","Clusters:");
        defaultEnglish.put("HDWT_entry251ClusterPanel","Selected:");
        defaultEnglish.put("HDWT_entry252ClusterPanel","Cluster");
        defaultEnglish.put("HDWT_entry253ClusterPanel","(size:");
        defaultEnglish.put("HDWT_entry254ClusterPanel","MSS value:");
        defaultEnglish.put("HDWT_entry255ClusterPanel","Show transition average firing");
        defaultEnglish.put("HDWT_entry256ClusterPanel","Show scaled colors");
        defaultEnglish.put("HDWT_entry257ClusterPanel","Show MCT sets");
        defaultEnglish.put("HDWT_entry258ClusterPanel","<html>&nbsp;Show&nbsp;<br>details</html>");
        defaultEnglish.put("HDWT_entry259ClusterPanel","<html>&nbsp;Export&nbsp;<br>pictures</html>");
        defaultEnglish.put("HDWT_entry260ClusterPanel","Completed");
        defaultEnglish.put("HDWT_entry261ClusterPanel","Cluster inv.:");
        defaultEnglish.put("HDWT_entry262ClusterPanel","<html>&nbsp;Time&nbsp;<br>details</html>");
        defaultEnglish.put("HDWT_entry263ClusterPanel","<html>&nbsp;Clusters&nbsp;<br>details</html>");
        defaultEnglish.put("HDWT_entry264ClusterPanel","Cluster:");
        defaultEnglish.put("HDWT_entry265ClusterPanel","inv.) alg.:");
        defaultEnglish.put("HDWT_entry266ClusterPanel","metric:");
        defaultEnglish.put("HDWT_entry267ClusterPanel","t-invariants and their time values:");
        defaultEnglish.put("HDWT_entry268ClusterPanel","Mean of average times:");
        defaultEnglish.put("HDWT_entry269ClusterPanel","Variance:");
        defaultEnglish.put("HDWT_entry270ClusterPanel","Standard deviation:");
        defaultEnglish.put("HDWT_entry271ClusterPanel","Cluster#");
        defaultEnglish.put("HDWT_entry272ClusterPanel","Select dir");
        defaultEnglish.put("HDWT_entry273ClusterPanel","Select directory for clusters screenshots.");
        defaultEnglish.put("HDWT_entry274ClusterPanel","Please click OK and wait until another window with information shows up.\nDepending on the number of clusters this should take from 10 seconds to 1 minute.\nPlease do not use the program until operation is finished.");
        defaultEnglish.put("HDWT_entry274ClusterPanel_t","Please wait");
        defaultEnglish.put("HDWT_entry275ClusterPanel","Saving clusters screenshots failed.");
        defaultEnglish.put("HDWT_entry276ClusterPanel","Saving");
        defaultEnglish.put("HDWT_entry276ClusterPanelb","clusters to graphic files completed.");
        defaultEnglish.put("HDWT_entry277ClusterPanel","Cluster:");
        defaultEnglish.put("HDWT_entry278ClusterPanel","inv.) alg.:");
        defaultEnglish.put("HDWT_entry279ClusterPanel","metric:");
        defaultEnglish.put("HDWT_entry280MCSPanel","Reaction:");
        defaultEnglish.put("HDWT_entry281MCSPanel","MCS:");
        defaultEnglish.put("HDWT_entry282MCSPanel","Refresh data");
        defaultEnglish.put("HDWT_entry283KnockPanel","Knockout:");
        defaultEnglish.put("HDWT_entry284KnockPanel","Knocked out:");
        defaultEnglish.put("HDWT_entry285KnockPanel","* * * Also knocked out: \n");
        defaultEnglish.put("HDWT_entry286FixPanel","t-invariants:");
        defaultEnglish.put("HDWT_entry287FixPanel","Normal: 0 / Non-inv.: 0");
        defaultEnglish.put("HDWT_entry288FixPanel","Sub-inv.: 0 / Sur-inv: 0");
        defaultEnglish.put("HDWT_entry289FixPanel","<html>Show<br>&nbsp;&nbsp;&nbsp;inv.</html>");
        defaultEnglish.put("HDWT_entry290FixPanel","Input and output places:");
        defaultEnglish.put("HDWT_entry291FixPanel","Input: 0 / Output: 0");
        defaultEnglish.put("HDWT_entry292FixPanel","<html>Show<br>places</html>");
        defaultEnglish.put("HDWT_entry293FixPanel","Input and output transitions:");
        defaultEnglish.put("HDWT_entry294FixPanel","Input: 0 / Output: 0");
        defaultEnglish.put("HDWT_entry295FixPanel","<html>Show<br>trans.</html>");
        defaultEnglish.put("HDWT_entry296FixPanel","Linear transitions and places");
        defaultEnglish.put("HDWT_entry297FixPanel","Transitions: 0 / Places: 0");
        defaultEnglish.put("HDWT_entry298FixPanel","<html>Show<br>T & P</html>");
        defaultEnglish.put("HDWT_entry299QuickSim","Compute steps from zero marking through the number of states");
        defaultEnglish.put("HDWT_entry300QuickSim","Set simulator options.");
        defaultEnglish.put("HDWT_entry301QuickSim","Data type simulated");
        defaultEnglish.put("HDWT_entry302QuickSim","Transitions firing data");
        defaultEnglish.put("HDWT_entry303QuickSim","Places tokens data");
        defaultEnglish.put("HDWT_entry304QuickSim","Color arcs");
        defaultEnglish.put("HDWT_entry305QuickSim","Repetitions");

        //DecoCalccalculator:
        defaultEnglish.put("DCC_entry001","Please choose comparison type");
        defaultEnglish.put("DCC_entry002","No t-invariants sets!");
        defaultEnglish.put("DCC_entry003","Second net: Invariants generated.\n");
        defaultEnglish.put("DCC_entry004","Second net: ADT generated.\n");
        defaultEnglish.put("DCC_entry005","Start comparison...\n");
        defaultEnglish.put("DCC_entry006","No t-nets sets!");
        defaultEnglish.put("DCC_entry007","Second net: T-net generated.\n");
        defaultEnglish.put("DCC_entry008","Start comparison...\n");
        defaultEnglish.put("DCC_entry009","No ADT sets!");
        defaultEnglish.put("DCC_entry010","Second net: Invariants generated.\n");
        defaultEnglish.put("DCC_entry011","Second net: ADT generated.\n");
        defaultEnglish.put("DCC_entry012","Start comparison...\n");
        defaultEnglish.put("DCC_entry013","No ADT sets!");
        defaultEnglish.put("DCC_entry014","Second net: Functional nets generated.\n");
        defaultEnglish.put("DCC_entry015","Start comparison...\n");

        //GDDAcalculator:
        defaultEnglish.put("GDDA_entry001","First net count...");
        defaultEnglish.put("GDDA_entry002","\nSecond net count... \n");
        defaultEnglish.put("GDDA_entry003","\nCalculate GDDA... \n");

        //GRDFcalculator:
        defaultEnglish.put("GRDF_entry001","Comparison process started. \n");
        defaultEnglish.put("GRDF_entry002","First net count... \n");
        defaultEnglish.put("GRDF_entry003","\nSecond net count... \n");
        defaultEnglish.put("GRDF_entry004","\nComparison process ended. \n");

        //InvariantsCalculator:
        defaultEnglish.put("IC_entry001","Invariants calculation started. \n");
        defaultEnglish.put("LOGentry00052","InvModule: Invariants generation failed.");
        defaultEnglish.put("IC_entry002","Invariants generation failed.\n");
        defaultEnglish.put("IC_entry003","Removing all non-canonical t-invariants from the dataset.");
        defaultEnglish.put("IC_entry004","non-canonical t-invariants has been removed:");
        defaultEnglish.put("IC_entry005","remained out of");
        defaultEnglish.put("IC_entry006","Removing all single-element t-invariants from the dataset.");
        defaultEnglish.put("IC_entry007","single-element t-invariants has been removed. t-invariants current size:");
        defaultEnglish.put("IC_entry008","Operation successfull, invariants found:");
        defaultEnglish.put("IC_entry009","Read-arcs detected. There are");
        defaultEnglish.put("IC_entry010","read-arcs in net.\n");
        defaultEnglish.put("IC_entry011","Feasible invariants computation/check is recommended. \n");
        defaultEnglish.put("IC_entry012","Warning: double arcs (read-arcs) detected between nodes:\n");
        defaultEnglish.put("IC_entry013","Place: p_");
        defaultEnglish.put("IC_entry014","and Transition t_");
        defaultEnglish.put("IC_entry015","Feasible invariants computation/check is recommended - depending on the set it may or may not change during this procedure.\n");
        defaultEnglish.put("IC_entry016","Checking t-invariants correctness for");
        defaultEnglish.put("IC_entry017","t-invariants.\n");
        defaultEnglish.put("IC_entry018","Real t-invariants (Cx = 0):");
        defaultEnglish.put("IC_entry019","Sur-t-invariants (Cx > 0):");
        defaultEnglish.put("IC_entry020","Sub-t-invariants (Cx < 0):");
        defaultEnglish.put("IC_entry021","Non-t-invariants (Cx <=> 0):");
        defaultEnglish.put("IC_entry022","Calculating difference...");
        defaultEnglish.put("IC_entry023","Difference set size:");
        defaultEnglish.put("IC_entry024","Removed");
        defaultEnglish.put("IC_entry025","t-invariants that were present in the current set.");
        defaultEnglish.put("IC_entry026","CSV below contains invariants that are not present in the currenly gerenerated set and have been present in the previously generated set.");
        defaultEnglish.put("IC_entry027","CSV set:");
        defaultEnglish.put("IC_entry028","Removing all non-canonical p-invariants from the dataset.");
        defaultEnglish.put("IC_entry029","non-canonical p-invariants has been removed:");
        defaultEnglish.put("IC_entry030","remained out of");
        defaultEnglish.put("IC_entry031","Operation successfull, invariants found:");
        defaultEnglish.put("IC_entry032","Warning: read-arcs detected. There are");
        defaultEnglish.put("IC_entry033","read-arcs in net.\n");
        defaultEnglish.put("IC_entry034","Double arcs (read-arcs) detected between nodes:\n");
        defaultEnglish.put("IC_entry035","Place: p_");
        defaultEnglish.put("IC_entry036","and Transition t_");
        defaultEnglish.put("IC_entry037","Checking p-invariants correctness for");
        defaultEnglish.put("IC_entry038","p-invariants.\n");
        defaultEnglish.put("IC_entry039","Proper p-invariants (Cx = 0):");
        defaultEnglish.put("IC_entry040","Sur-p-invariants (Cx > 0):");
        defaultEnglish.put("IC_entry041","Sub-p-invariants (Cx < 0):");
        defaultEnglish.put("IC_entry042","Non-p-invariants (Cx <=> 0):");
        defaultEnglish.put("LOGentry00053","InvModule: Invariants generation failed.");
        defaultEnglish.put("IC_entry043","Invariants generation failed.\n");
        defaultEnglish.put("IC_entry044","\nTP-class incidence matrix created for");
        defaultEnglish.put("IC_entry045","transitions and");
        defaultEnglish.put("IC_entry046","places.\n");
        defaultEnglish.put("IC_entry047","Identity matrix created for");
        defaultEnglish.put("IC_entry048","transitions.\n");
        defaultEnglish.put("IC_entry049","No incidence matrix. Terminating.\n");
        defaultEnglish.put("IC_entry050","Phase I inititated. Performing only for all 1-in/1-out columns.\n");
        defaultEnglish.put("IC_entry051","Processing simple-class column:");
        defaultEnglish.put("IC_entry052","Processing column:");
        defaultEnglish.put("IC_entry053",", projected rows change:");
        defaultEnglish.put("IC_entry054",", remaining steps:");
        defaultEnglish.put("IC_entry055","\nNew rows number:");
        defaultEnglish.put("IC_entry056","| rejected:");
        defaultEnglish.put("IC_entry057","replaced:");
        defaultEnglish.put("IC_entry058","not canonical:");
        defaultEnglish.put("IC_entry059","Phase I inititated. Performing only for all 1-in/1-out columns.\n");
        defaultEnglish.put("IC_entry060","Processing simple-class column:");
        defaultEnglish.put("LOGentry00054error","Critical error (2000001) calculating invariants.");
        defaultEnglish.put("LOGentry00055error","CheckCoverability function, catastrophic error (2000002): impossible state detected.");

        //generalPurposeTags:
        defaultEnglish.put("cancel","Cancel");
        defaultEnglish.put("critError","Critical error");
        defaultEnglish.put("confirm","Confirm");
        defaultEnglish.put("continue","Continue");
        defaultEnglish.put("error","Error");
        defaultEnglish.put("exit","Exit");
        defaultEnglish.put("fixed","Fixed");
        defaultEnglish.put("problem","Problem");
        defaultEnglish.put("saveAndExit","Save and Exit");
        defaultEnglish.put("saveAndCont","Save and continue");
        defaultEnglish.put("save","Save");
        defaultEnglish.put("select","Select");
        defaultEnglish.put("netSimWork01","Net simulator working");
        defaultEnglish.put("unimplemented","Not implemented yet.");
        defaultEnglish.put("unimplementedTitle","Subsystem offline");
        

        return defaultEnglish;
    }
}
