package abyss.darkgui.dockable;

import javax.swing.JCheckBoxMenuItem;


import com.javadocking.dockable.Dockable;

/**
 * A check box menu item to add or remove the dockable.
 */
public class DockableMenuItem extends JCheckBoxMenuItem {
	/**
	 * autogenerated serial
	 */
	private static final long serialVersionUID = -690559183213842322L;

	public DockableMenuItem(Dockable dockable) {
		super(dockable.getTitle(), dockable.getIcon());

		setSelected(dockable.getDock() != null);

		DockableMediator dockableMediator = new DockableMediator(dockable, this);
		dockable.addDockingListener(dockableMediator);
		addItemListener(dockableMediator);
	}
}